#-------------------------------
# General Site Settings

title: OMM
logo: "assets/images/favicon.png"
author: Rodrigo Cortez
description:  Olimpiada Michoacana de Matemáticas

email: olimpiada.omm@gmail.com
#phone: +52 4433223500 ext. 1230
address: Morelia, Michoacán.
copyright: "Designed by <a href='https://roicort.github.io'>Rodrigo Cortez</a> with <a href='/opensource'>OSS</a> <br> Made with ❤️ in Morelia <br> Copyright &copy; 2021"

menu:
- {name: Inicio, link: '/'}
- {name: Acerca, link: '/acerca'}
# - {name: Rifa, link: '/rifa'}
- {name: Resultados, link: '/resultados'}
- {name: Convocatoria 2025, link: '/convocatoria'}
- {name: Prepárate, link: '/preparate'}
#- {name: Póster, link: '/poster'}
#- {name: Noticias, link: '/noticias'}
#- {name: Resultados, link: '/resultados'}
#- {name: Registro, link: '/registro'}

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: G-RQ5FK6LMMN


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Olimpiada <br> Michoacana <br> de Matemáticas

social:
- {icon: "ti-facebook", link: "https://www.facebook.com/olimpiadamichoacanadematematicas"}
- {icon: "ti-instagram", link: "https://www.facebook.com/olimpiadamichoacanadematematicas"}
- {icon: "ti-themify-favicon", link: "https://chat.whatsapp.com/EusFmjYySlF2E8tmZPZHss"} 
#- {icon: "ti-dribbble", link: "#"}
#- {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  El objetivo de la Olimpiada de Matemáticas es promover el estudio de las matemáticas en forma creativa, lógica y divertida, buscando desarrollar el razonamiento y la imaginación.

blurb-btn-link: '/acerca'
blurb-btn-name: Más

# Work Process Section
#work-process:
  #- title : "OMM"
    #icon : "assets/images/icons/favicon.png"
    #content : "Olimpiada Michoacana de Matemáticas: Desde pequeños hasta 2do de preparatoria o equivalente."
    
  #- title : "OMMEB"
    #icon : "assets/images/icons/logo-2.png"
    #content : "Olimpiada Michoacana de Matemáticas para Educación Básica: Desde 4to de primaria hasta 2do de secundaria."
    

# My Team Section
team:
  - title : "Miguel Raggi"
    image : "assets/images/team/miguel.jpg"
    designation : "Delegado, Profesor ENES, ex-olímpico"
    
  - title : "María del Río"
    image : "assets/images/team/maria.jpg"
    designation : "Codelegada, Coordinadora Físico-Matemáticas ENES"

  - title : "María Luisa Pérez"
    image : "assets/images/team/malu.jpg"
    designation : "Profesora UMSNH"

  - title : "Nelly Selem"
    image : "assets/images/team/nelly.jpg"
    designation : "Investigadora, Centro de Ciencias Matemáticas"
    
  - title : "Edgardo Roldán"
    image : "assets/images/team/edgardo.jpg"
    designation: "Investigador, Centro de Ciencias Matemáticas"
    
  - title : "Manuel Alejandro Espinoza"
    image : "assets/images/team/prima.jpg"
    designation : "Estudiante Doctoral CCM, ex-olímpico"
           
  - title : "Arnoldo Chue"
    image : "assets/images/team/arnoldo.jpg"
    designation : "Estudiante de LTICs, 4to semestre / Servicio Social"
    
  - title : "Ashley Aguilar"
    image : "assets/images/team/ash.jpg"
    designation : "Estudiante de LTICs, 6to semestre / Servicio Social"
    
  - title : "Alondra Juárez"
    image : "assets/images/team/alondra.jpg"
    designation : "Artista, Diseñadora, Ex-olímpica"
  
  - title : "Gerardo Zabdiel Martinez Zavala"
    image : "assets/images/team/Zabdiel.jpg"
    designation : "Estudiante de LTICs, 6to semestre / Servicio Social"
    
# Entrenadores
entrenadores:
  - title : "Luis Miguel García"
    image : "assets/images/team/luismiguel.jpg"
    designation : "Profesor ENES, ex-olímpico"

  - title : "Jorge Luis López López"
    image : "assets/images/team/jorge.jpg"
    designation: "Profesor UMSNH"
    
  - title : "Adriana Menchaca"
    image : "assets/images/team/adriana.jpg"
    designation : "Profesora, ENES Morelia"
    
  - title : "Héctor Alonso Guzmán"
    image : "assets/images/team/hectoralonso.jpg"
    designation : "Profesor, ENES Morelia"
    
  - title : "Paola González"
    image : "assets/images/team/paola.jpg"
    designation : "Graduada LTICs, ENES Morelia"
        
  - title : "Kaori Ureña"
    image : "assets/images/team/kaori.jpg"
    designation : "Ex-olímpica, Selección Michoacana"

  - title : "Bialy Calderón Magaña"
    image : "assets/images/team/bialy.jpg"
    designation : "Ex-olímpica, Selección Michoacana"
    
  - title : "Miguel Rangel Castillo"
    image : "assets/images/team/mike.jpg"
    designation : "Ex-olímpico, Selección Michoacana"
    
  - title : "Alexis Aguilar"
    image : "assets/images/team/alexis.jpg"
    designation : "Estudiante de LTICs, 2do semestre / Ex-olímpico, Selección Michoacana"
    
  - title : "Luis Alberto García"
    image : "assets/images/team/luisalberto.jpg"
    designation : "Estudiante de LTICs, 2do semestre / Ex-olímpico, Selección Michoacana"


  - title : "Marisol Flores"
    image : "assets/images/team/marisol.jpg"
    designation : "Profesora, ENES Morelia"
    
exmiembros:
  - title : "Rodrigo Cortez"
    image : "assets/images/team/rodrigo.jpg"
    designation : "Egresado LTICs ENES - IT Consultant"
    
  - title : "Ismael Olvera"
    image : "assets/images/team/ismael.jpg"
    designation : "Estudiante LTICs ENES - IT Consultant"
  
  - title : "Jazmín López Chacón"
    image : "assets/images/team/jazmin.jpg"
    designation : "Estudiante, Tecnologías para la Información en Ciencias"
    
  - title : "Alex Martínez"
    image : "assets/images/team/alex.jpg"
    designation : "Estudiante de matemáticas. Ex-olímpico"
    
  - title : "César Corral"
    image : "assets/images/team/cesar.jpg"
    designation: "Estudiante"
    
  - title : "Antonio Montero"
    image : "assets/images/team/tero.jpg"
    designation : "Posdoc UNAM"
    
  - title : "Rubén Maldonado"
    image : "assets/images/team/ruben.jpg"
    designation: "Estudiante"
    
  - title : "Eduardo Ceja"
    image : "assets/images/team/lalo.jpg"
    designation: "Egresado LTICs / Servicio Social"
    
  - title : "Saul Armas"
    image : "assets/images/team/saul.jpg"
    designation: "Egresado LTICs / Servicio Social"
    
  - title : "Francisco Fonseca"
    image : "assets/images/team/fonseca.jpg"
    designation: "Egresado LTICs / Servicio Social"
    
  - title : "Mirna Gómez"
    image : "assets/images/team/mirna.jpg"
    designation: "Profesora, ENES Morelia"
    
  - title : "Eric Pauli"
    image : "assets/images/team/eric.jpg"
    designation : "Doctor en Matemáticas"
    
#-------------------------------
# Stats Section

stats-title: Stats
stats:
- {name: Web Design, color: '#fdb157', value: '90%'}
- {name: Logo Design, color: '#9473e6', value: '60%'}
- {name: After Effects, color: '#bdecf6', value: '80%'}
- {name: Web App, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Events Section

# events:
# - {name: <a href="/convocatoria">Examen inicial 2025</a>, icon: 'logo-3.png', date: '1-3 febrero 2025', organization: '<br>¡Para todas las categorías!<br><br><a href="/preparate">¡Prepárate!</a></br>'}


#-------------------------------
# Archivements Section

#archivement:
#- {name: Se inauguran las primeras OMM, date: '1986', organization: 'CIMAT'}
#- {name: Miguel Raggi se hace cargo, date: '2021', organization: 'UMSNH'}
#- {name: Hacemos una página bien chida, date: '2021', organization: 'Mi Casa'}
#- {name: Resolvemos el analfabetismo matemático, date: '2022', organization: 'Planeta Tierra'}



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
#portfolio-home-items:
  #- image : "assets/images/portfolio/item-1.png"
    #url: "#"
    
  #- image : "assets/images/portfolio/item-2.png"
    #url: "#"
    
  #- image : "assets/images/portfolio/item-3.png"
    #url: "#"
    
  #- image : "assets/images/portfolio/item-4.png"
    #url: "#"
    
  #- image : "assets/images/portfolio/item-5.png"
    #url: "#"


## Portfolio Page
#portfolio-label:
#- {
    #title : "Problemas",
    #type : "design"
  #}
#- {
    #title : "Examenes Deamentis",
    #type : "branding"
  #}
#- {
    #title : "Juegos",
    #type : "illustration"
  #}

#portfolio-items:
  #- image : "assets/images/portfolio/item-1.png"
    #url: "#"
    #portfolio-type:
     #- type: "design"
     #- type: "illustration"
      
  #- image : "assets/images/portfolio/item-2.png"
    #url: "#"
    #portfolio-type:
      #- type: "branding"
      
  #- image : "assets/images/portfolio/item-3.png"
    #url: "#"
    #portfolio-type:
      #- type: "illustration"
      
  #- image : "assets/images/portfolio/item-6.png"
    #url: "#"
    #portfolio-type:
      #- type: "design"
      #- type: "branding"
      
  #- image : "assets/images/portfolio/item-8.png"
    #url: "#"
    #portfolio-type:
      #- type: "illustration"
      
  #- image : "assets/images/portfolio/item-5.png"
    #url: "#"
    #portfolio-type:
      #- type: "design"
      
  #- image : "assets/images/portfolio/item-1.png"
    #url: "#"
    #portfolio-type:
      #- type: "branding"
      
  #- image : "assets/images/portfolio/item-3.png"
    #url: "#"
    #portfolio-type:
      #- type: "design"
      #- type: "illustration"
      #- type: "branding"
      
  #- image : "assets/images/portfolio/item-7.png"
    #url: "#"
    #portfolio-type:
      #- type: "illustration"

      

#-------------------------------
# Services Section

services-title: Problemas de Ejemplo
services:

- {
    name: '<img src="assets/images/problemas/tablaSumas.png" width=95%>',
    #icon: ti-vector,
    description: 'A mi tabla de sumas le cayó tinta encima. ¿Qué número debe ir en lugar de la estrella?',
    active:  false # Add true to select section
  }
  
- {
    name: '<img src="assets/images/problemas/cubosPagina.png" width=95%>',
    #icon: 'assets/images/problemas/cubosPagina.png',
    description: '¿Cuántos cubitos más deben agregarse para formar un cubo más grande?',
    active:  false # Add true to select section
  }
  
- {
    name: '<img src="assets/images/problemas/pentagono.png" width=95%>',
    #icon: ti-panel,
    description: '¿Qué porcentaje del pentágono está sombreado?',
    active: false # Add true to select section
  }



#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Alondra Juárez"
    image: "assets/images/testimonial/client3.png"
    designation : "Ex-olímpica, cofundadora de la OMMEB en Michoacán"
    content : "Aprendía más en dos meses de olímpica que en un año de escuela."

  - name: "Moisés Pelayo"
    image: "assets/images/testimonial/client5.png"
    designation : "Ex-olímpico"
    content : "La olimpiada es la segunda mejor cosa que me ha pasado... <br>la primera es las personas que ahí conocí."

  - name: "Manuel Alejandro Espinoza"
    image: "assets/images/testimonial/client1.png"
    designation : "Ex-olímpico y entrenador de la delegación"
    content : "La olimpiada cambió mi vida."
    
  - name: "Margarita Godínez"
    image: "assets/images/testimonial/client2.png"
    designation : "Ex-olímpica"
    content : "La verdad me confundí pensando que esta era una olimpiada de atletismo, pero las matemáticas estuvieron mejores."
    
  - name: "Hugo Gómez"
    image: "assets/images/testimonial/client4.png"
    designation : "Ex-olímpico"
    content : "Es una experiencia que cambia tu visión de las matemáticas como nunca las podrás ver en la escuela."

  - name: "Nicolás Valdovinos"
    image: "assets/images/testimonial/client6.png"
    designation : "Ex-olímpico"
    content : "Un lugar lleno de nuevos retos y personas emocionantes."
    
#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/enes.png"
    url: "https://www.enesmorelia.unam.mx"
    
  - logo: "assets/images/clients-logo/unam.png"
    url: "https://www.unam.mx"
    
  - logo: "assets/images/clients-logo/canguro.png"
    url: "#"

  - logo: "assets/images/clients-logo/ccm.png"
    url: "https://www.matmor.unam.mx"
    
  - logo: "assets/images/clients-logo/umsnh.png"
    url: "https://www.umich.mx"

  - logo: "assets/images/clients-logo/ICTI.png"
    url: "https://icti.michoacan.gob.mx/"

  - logo: "assets/images/clients-logo/CCUNAM.png"
    url: "https://www.enesmorelia.unam.mx/unam-centro-cultural-morelia/"
    
  - logo: "assets/images/clients-logo/smm.png" #Important!
    url: "https://www.smm.org.mx" #Se necesita esta cantidad de Logos para que funcione el carrousel.

  - logo: "assets/images/clients-logo/enes.png"
    url: "https://www.enesmorelia.unam.mx"
    
  - logo: "assets/images/clients-logo/unam.png"
    url: "https://www.unam.mx"
    
  - logo: "assets/images/clients-logo/canguro.png"
    url: "#"

  - logo: "assets/images/clients-logo/ccm.png"
    url: "https://www.matmor.unam.mx"
    
  - logo: "assets/images/clients-logo/umsnh.png"
    url: "https://www.umich.mx"
    
  - logo: "assets/images/clients-logo/smm.png"
    url: "https://www.smm.org.mx"

  - logo: "assets/images/clients-logo/ICTI.png"
    url: "https://icti.michoacan.gob.mx/"
