#-------------------------------
# General Site Settings

title: OMM
logo: "assets/images/favicon.png"
author: Rodrigo Cortez
description:  Olimpiada Michoacana de Matemáticas

email: olimpiada.omm@gmail.com
#phone: +52 4433223500 ext. 1230
address: Escuela Nacional de Estudios Superiores, Oficina 48, Edificio de Investigación.
copyright: "Designed by <a href='https://roicort.github.io'>Rodrigo Cortez</a> - Boilerplate by <a href='https://google.com'>ThemeFisher</a> <br> Made with ❤️ in Morelia <br> Copyright &copy; 2021"

menu:
- {name: Convocatoria, link: '/convocatoria'}
#- {name: OMM, link: '/omm'}
#- {name: OMMEB, link: '/ommeb'}
- {name: Acerca, link: '/acerca'}
- {name: Noticias, link: '/noticias'}
- {name: Prepárate, link: 'https://www.ommenlinea.org/'}
- {name: Registro, link: '/registro'}


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: G-RQ5FK6LMMN


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Olimpiada <br> Michoacana <br> de Matemáticas

social:
#- {icon: "ti-facebook", link: "#"}
#- {icon: "ti-instagram", link: "#"}
#- {icon: "ti-dribbble", link: "#"}
#- {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
  El objetivo de la Olimpiada de Matemáticas es promover el estudio de las matemáticas en forma creativa, lógica y divertida, buscando desarrollar el razonamiento y la imaginación de los jóvenes.

blurb-btn-link: '/acerca'
blurb-btn-name: Más

# Work Process Section
work-process:
  - title : "OMM"
    icon : "assets/images/icons/favicon.png"
    content : "Olimpiada Michoacana de Matemáticas: Desde pequeños hasta 2do de preparatoria o equivalente."
    
  - title : "OMMEB"
    icon : "assets/images/icons/logo-2.png"
    content : "Olimpiada Michoacana de Matemáticas para Educación Básica: Desde 4to de primaria hasta 2do de secundaria."
    

# My Team Section
team:
  - title : "Miguel Raggi"
    image : "assets/images/team/miguel.jpg"
    designation : "Delegado, Profesor ENES, ex-olímpico"
    
  - title : "María del Río"
    image : "assets/images/team/maria.jpg"
    designation : "Codelegada, Coordinadora Físico-Matemáticas ENES"
    
  - title : "Manuel Alejandro Espinoza"
    image : "assets/images/team/prima.jpg"
    designation : "Estudiante Doctoral CCM, ex-olímpico"
    
  - title : "María Luisa Pérez"
    image : "assets/images/team/malu.jpg"
    designation : "Profesora UMSNH"
    
  - title : "Luis Miguel García"
    image : "assets/images/team/luismiguel.jpg"
    designation : "Profesor ENES, ex-olímpico"
    
  - title : "Rodrigo Cortez"
    image : "assets/images/team/rodrigo.jpg"
    designation : "Estudiante LTICs ENES, web designer"
    
  - title : "Alondra Juárez"
    image : "assets/images/team/alondra.jpg"
    designation : "Estudiante Arte y Diseño ENES, ex-olímpica"
    
  - title : "Ismael Olvera"
    image : "assets/images/team/ismael.jpg"
    designation : "Estudiante LTICs ENES"

    
  - title : "Eric Pauli"
    image : "assets/images/team/eric.jpg"
    designation : "Posdoc en Centro de Ciencias Matemáticas"
    
  - title : "Jazmín López"
    image : "assets/images/team/jazmin.jpg"
    designation : "Estudiante LTICs ENES"


#-------------------------------
# Stats Section

stats-title: Stats
stats:
- {name: Web Design, color: '#fdb157', value: '90%'}
- {name: Logo Design, color: '#9473e6', value: '60%'}
- {name: After Effects, color: '#bdecf6', value: '80%'}
- {name: Web App, color: '#ffbcaa', value: '70%'}


#-------------------------------
# Events Section

events:
- {name: Eliminatoria Primera Vuelta, icon: 'logo-1.png', date: '20-21 Marzo 2021', organization: 'Online'}
- {name: Eliminatoria Segunda Vuelta, icon: 'logo-2.png', date: '3-4 Abril 2021', organization: 'Online'}
#- {name: Semifinal OMM, icon: 'icon-2.png', date: 'Abril 2021', organization: 'ENES Morelia'}
#- {name: Final OMM, icon: 'icon-3.png', date: 'Mayo 2021', organization: 'UMICH'}


#-------------------------------
# Archivements Section

#archivement:
#- {name: Se inauguran las primeras OMM, date: '1986', organization: 'CIMAT'}
#- {name: Miguel Raggi se hace cargo, date: '2021', organization: 'UMSNH'}
#- {name: Hacemos una página bien chida, date: '2021', organization: 'Mi Casa'}
#- {name: Resolvemos el analfabetismo matemático, date: '2022', organization: 'Planeta Tierra'}


#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: Estudiantes,
    icon: ti-palette,
    description: 'Impulsamos a los estudiantes para que logren todas sus metras',
    active: # Add true to select section
  }
- {
    name: Matemáticas,
    icon: ti-vector,
    description: 'Fortalecemos el pensamiento científico y el pensamiento crítico',
    active: true # Add true to select section
  }
- {
    name: Comunidad olímpica,
    icon: ti-panel,
    description: 'Las matematicas tambien nos conectan.',
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-5.png"
    url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "Problemas",
    type : "design"
  }
- {
    title : "Examenes Deamentis",
    type : "branding"
  }
- {
    title : "Juegos",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"


#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Manuel Alejandro Espinoza"
    image: "assets/images/testimonial/prima.jpg"
    designation : "Ex-olímpico y entrenador de la delegación"
    content : "La olimpiada cambió mi vida."
    
  - name: "Héctor de la Rosa"
    image: "assets/images/testimonial/hector.jpg"
    designation : "Ex-olímpico, cofundador de la OMMEB en Michoacán"
    content : "La verdad me confundí pensando que esta era una olimpiada de atletismo, pero las matemáticas estuvieron mejores."
    
  - name: "Alondra Juárez"
    image: "assets/images/testimonial/alondra.png"
    designation : "Ex-olímpica, cofundadora de la OMMEB en Michoacán"
    content : "Estuvo súper chevere, 15 de 10."


#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/enes.png"
    url: "www.enesmorelia.unam.mx"
    
  - logo: "assets/images/clients-logo/umich.png"
    url: "www.umich.mx"
    
  - logo: "assets/images/clients-logo/ccm.jpg"
    url: "www.matmor.unam.mx"
    
  - logo: "assets/images/clients-logo/smm.png"
    url: "www.smm.org.mx"
    
  - logo: "assets/images/clients-logo/enes.png"
    url: "www.enesmorelia.unam.mx"
    
  - logo: "assets/images/clients-logo/umich.png"
    url: "www.umich.mx"
    
  - logo: "assets/images/clients-logo/unam.png"
    url: "www.unam.mx"
    
  - logo: "assets/images/clients-logo/smm.png"
    url: "www.smm.org.mx"
    
  - logo: "assets/images/clients-logo/ccm.jpg"
    url: "www.matmor.unam.mx"
    
  - logo: "assets/images/clients-logo/enes.png"
    url: "www.enesmorelia.unam.mx"
    
  - logo: "assets/images/clients-logo/umich.png"
    url: "www.umich.mx"
    
  - logo: "assets/images/clients-logo/smm.png"
    url: "www.smm.org.mx"
    
  - logo: "assets/images/clients-logo/unam.png"
    url: "www.unam.mx"
    
  - logo: "assets/images/clients-logo/ccm.jpg"
    url: "www.matmor.unam.mx"
    
  - logo: "assets/images/clients-logo/enes.png"
    url: "www.enesmorelia.unam.mx"
    
  - logo: "assets/images/clients-logo/smm.png"
    url: "www.smm.org.mx"
